"use client";

import { useState } from "react";
import { Search, Timer, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import type { RetrievalCandidate, RetrievalTrace } from "@/lib/server/v2/retrieval/types";

const CandidateTable = ({ title, rows }: { title: string; rows: RetrievalCandidate[] }) => <Card><CardHeader><CardTitle className="text-base">{title} <span className="text-muted-foreground">({rows.length})</span></CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="p-2">#</th><th className="p-2">知识</th><th className="p-2">标题</th><th className="p-2">类型</th><th className="p-2">全文</th><th className="p-2">向量</th><th className="p-2">RRF</th><th className="p-2">Rerank</th></tr></thead><tbody>{rows.map((row, index) => <tr className="border-b" key={row.chunkId}><td className="p-2">{index + 1}</td><td className="p-2 font-mono text-xs">{row.chunkId}</td><td className="p-2">{row.title}</td><td className="p-2">{row.knowledgeType}</td><td className="p-2">{row.textScore.toFixed(3)}</td><td className="p-2">{row.vectorScore.toFixed(3)}</td><td className="p-2">{row.rrfScore.toFixed(4)}</td><td className="p-2 font-semibold">{row.rerankScore.toFixed(3)}</td></tr>)}</tbody></table></CardContent></Card>;

export default function RetrievalDebugPage() {
  const [question, setQuestion] = useState("Como criar um perfil de navegador?"); const [product, setProduct] = useState("dicloak"); const [trace, setTrace] = useState<RetrievalTrace | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const run = async () => { setLoading(true); setError(""); try { const response = await fetch("/api/v2/retrieval-debug", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ question, product }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "检索失败"); setTrace(payload); } catch (caught) { setError(caught instanceof Error ? caught.message : String(caught)); } finally { setLoading(false); } };
  return <main className="min-h-screen bg-slate-50 p-6 text-slate-900"><div className="mx-auto max-w-[1500px] space-y-5"><div><p className="text-sm font-medium text-cyan-700">INTERNAL · V2 RETRIEVAL</p><h1 className="text-3xl font-bold">混合检索调试台</h1><p className="text-muted-foreground">仅检查知识选择，不生成客户回复。</p></div><Card><CardContent className="flex flex-col gap-3 pt-6 md:flex-row"><Input value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void run(); }} className="flex-1"/><Select value={product} onValueChange={setProduct}><SelectTrigger className="w-44"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="dicloak">DICloak</SelectItem><SelectItem value="paraturbo">Paraturbo</SelectItem></SelectContent></Select><Button onClick={() => void run()} disabled={loading}><Search className="mr-2 size-4"/>{loading ? "检索中" : "运行检索"}</Button></CardContent></Card>{error && <p className="rounded-lg bg-red-50 p-3 text-red-700">{error}</p>}{trace && <><div className="grid gap-4 md:grid-cols-4"><Card><CardContent className="pt-5"><ShieldCheck className="mb-2 size-5 text-cyan-700"/><p className="text-xs text-muted-foreground">置信度</p><p className="text-2xl font-bold uppercase">{trace.confidence}</p></CardContent></Card><Card><CardContent className="pt-5"><Timer className="mb-2 size-5 text-cyan-700"/><p className="text-xs text-muted-foreground">总耗时</p><p className="text-2xl font-bold">{trace.timings.total} ms</p></CardContent></Card><Card className="md:col-span-2"><CardContent className="pt-5"><p className="text-xs text-muted-foreground">硬过滤</p><p className="mt-2 text-sm">{trace.filteredReasons.join(" · ")}</p><p className="mt-2 text-xs text-amber-700">{trace.confidenceReasons.join("；")}</p></CardContent></Card></div><Card><CardHeader><CardTitle className="text-base">查询结构</CardTitle></CardHeader><CardContent><pre className="overflow-auto rounded-lg bg-slate-950 p-4 text-xs text-slate-100">{JSON.stringify({ question: trace.question, intent: trace.intent, filters: trace.filters, degradedRoutes: trace.degradedRoutes, timings: trace.timings }, null, 2)}</pre></CardContent></Card><div className="grid gap-5 xl:grid-cols-2"><CandidateTable title="全文召回" rows={trace.fulltext.slice(0, 10)}/><CandidateTable title="向量召回" rows={trace.vector.slice(0, 10)}/></div><CandidateTable title="RRF 融合" rows={trace.fused}/><CandidateTable title="Rerank 后 Top 1–5" rows={trace.top}/></>}</div></main>;
}
